### ISSUE TITLE
Issue where put back is executed upon enter key on permanently delete dialog

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/ComponentDB#832]

**Comment by craigmcchesney** [comment]
Dariusz reported an odd behavior where if you put the keyboard focus in the text input field of the confirmation dialog for the permanently remove operation, the restore operation is run instead and the item is returned to the regular item list view.

This appears to be due to the fact that there is a single input text field, and in that case the form is submitted when the enter key pressed.  Because the button for the restore deleted item dialog is the first button, that action is performed when the form is submitted.  The fix would seem to be just reordering the dialogs in the file, so that the one with the input text field is first and the button on that same dialog is the first button encountered when the form is submitted.  This also seems like a hack and I don't love the solution.

contextMenuSupport.xhtml:
reordered dialogs so that the permanently delete dialog, which has the input text field, is first in the file and the restore dialog is second.  This way, the default action on submitting the form will be the permanently remove action.
